# Site Settings
title:               Lagrange
tagline:             a minimalist Jekyll theme
description:
baseurl:            #"/Lagrange"
url: 			#"http://www.seahdavid.com"
github:
url: 		"http://www.seahdavid.com"
author:
  name:              "Paul Le"
  email:             "l.nguyen.paul@gmail.com"
  twitter:           "paululele"
  instagram:         
  github:            
  facebook:          
  linkedin:          
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
